inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/EmptyLinesAroundAttributeAccessor: # (0.83)
  Enabled: true

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Packaging/RequireRelativeHardcodingLib:
  Exclude:
    - bin/**/*
    - spec/**/*
