name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to Rubygems
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up latest Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
